package github

import (
	"fmt"
	"path/filepath"
	"strings"
)

const DefaultDiffChunkBytes = 120_000

var generatedFileMarkers = []string{
	"code generated",
	"do not edit",
	"auto-generated",
	"autogenerated",
}

func BuildDiff(files []PullRequestFile) string {
	return strings.Join(BuildDiffChunks(files, DefaultDiffChunkBytes), "\n")
}

func BuildDiffChunks(files []PullRequestFile, maxBytes int) []string {
	if maxBytes <= 0 {
		maxBytes = DefaultDiffChunkBytes
	}

	var chunks []string
	var builder strings.Builder
	for _, file := range files {
		if !ReviewableFile(file) {
			continue
		}

		fileDiff := formatFileDiff(file)
		if builder.Len() > 0 && builder.Len()+len(fileDiff) > maxBytes {
			chunks = append(chunks, builder.String())
			builder.Reset()
		}
		if len(fileDiff) > maxBytes {
			chunks = append(chunks, fileDiff)
			continue
		}
		builder.WriteString(fileDiff)
	}

	if builder.Len() > 0 {
		chunks = append(chunks, builder.String())
	}

	for i := range chunks {
		if len(chunks) > 1 {
			chunks[i] = fmt.Sprintf("OpenReview diff chunk %d/%d\n%s", i+1, len(chunks), chunks[i])
		}
	}

	return chunks
}

func formatFileDiff(file PullRequestFile) string {
	var builder strings.Builder
	builder.WriteString("diff --git a/")
	builder.WriteString(file.Filename)
	builder.WriteString(" b/")
	builder.WriteString(file.Filename)
	builder.WriteByte('\n')
	builder.WriteString(file.Patch)
	if !strings.HasSuffix(file.Patch, "\n") {
		builder.WriteByte('\n')
	}
	return builder.String()
}

func ReviewableFile(file PullRequestFile) bool {
	if strings.TrimSpace(file.Patch) == "" {
		return false
	}
	if file.Status == "removed" {
		return false
	}
	if IsGeneratedFile(file.Filename, file.Patch) {
		return false
	}
	return SupportedFile(file.Filename)
}

func SupportedFile(path string) bool {
	switch strings.ToLower(filepath.Ext(path)) {
	case ".go", ".js", ".jsx", ".ts", ".tsx", ".py", ".cs", ".java", ".rb", ".php", ".rs", ".sql", ".yaml", ".yml", ".json", ".tf", ".Dockerfile":
		return true
	default:
		return strings.EqualFold(filepath.Base(path), "Dockerfile")
	}
}

func IsGeneratedFile(path string, patch string) bool {
	base := strings.ToLower(filepath.Base(path))
	if strings.Contains(base, "generated") || strings.HasSuffix(base, ".pb.go") || strings.HasSuffix(base, ".gen.go") {
		return true
	}

	lowerPatch := strings.ToLower(patch)
	for _, marker := range generatedFileMarkers {
		if strings.Contains(lowerPatch, marker) {
			return true
		}
	}
	return false
}

func ChangedLinesByFile(files []PullRequestFile) map[string]map[int]struct{} {
	result := make(map[string]map[int]struct{})
	for _, file := range files {
		if !ReviewableFile(file) {
			continue
		}
		lines := ChangedLines(file.Patch)
		if len(lines) > 0 {
			result[file.Filename] = lines
		}
	}
	return result
}

func ChangedLines(patch string) map[int]struct{} {
	changed := make(map[int]struct{})
	var newLine int

	for _, line := range strings.Split(patch, "\n") {
		if strings.HasPrefix(line, "@@") {
			parsed, ok := parseNewFileStart(line)
			if ok {
				newLine = parsed
			}
			continue
		}
		if newLine == 0 {
			continue
		}
		if strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "+++") {
			changed[newLine] = struct{}{}
			newLine++
			continue
		}
		if strings.HasPrefix(line, "-") && !strings.HasPrefix(line, "---") {
			continue
		}
		newLine++
	}

	return changed
}

func parseNewFileStart(hunkHeader string) (int, bool) {
	var oldStart, oldCount, newStart, newCount int
	if _, err := fmt.Sscanf(hunkHeader, "@@ -%d,%d +%d,%d @@", &oldStart, &oldCount, &newStart, &newCount); err == nil {
		return newStart, true
	}
	if _, err := fmt.Sscanf(hunkHeader, "@@ -%d +%d @@", &oldStart, &newStart); err == nil {
		return newStart, true
	}
	if _, err := fmt.Sscanf(hunkHeader, "@@ -%d,%d +%d @@", &oldStart, &oldCount, &newStart); err == nil {
		return newStart, true
	}
	return 0, false
}
